### ISSUE TITLE
beef install

### ISSUE THREAD

**Issue by sh1va73** [AzizKpln/Beef-Over-AWS#2]
Today I tested Beef-over-AWS and it works very good. Only I want to ask why I have to install beef again.
Already it was installed on my system but now I needed to install beef again in beef-over-aws folder. Just want to know why this is so.

**Comment by AzizKpln** [comment]
Hi,
Beef has to be in beef_over_aws/ folder because my algorithm requires it. Beef_over_aws sets up the Beef tool from the scratch for ubuntu and Debian based systems but it doesn't check if the Beef has been installed before. That feature can be added in the new version but currently, tool works the way it should. Therefore, im not gonna bother myself for a new release soon. 

(Btw, u don't have to install anything because my tool does every installation by itself automatically.)

**Comment by sh1va73** [comment]
Thanks for the reply. Yes the tool install everything automatically. No issue.
