### ISSUE TITLE
Report #1

### ISSUE THREAD

**Issue by Clqn** [AzizKpln/Beef-Over-AWS#3]
Hey Aziz I was using your project and everything went well I ran the program waited a few minutes for everything to download and the installation went well after I did this I ran the  program and I cd to /var/www/html and edited index.html after that I tried going to my local ip which is 10.0.2.15 and it said could not connect to page any help is appreciated

In turkish to make it easier for you: 

Hey Aziz Projenizi kullanıyordum ve her şey yolunda gitti Programı çalıştırdım her şeyin indirilmesi için birkaç dakika bekledim ve bunu yaptıktan sonra kurulum iyi gitti, programı çalıştırdım ve / var / www / html'ye cd yazdım ve dizini düzenledim. html ondan sonra 10.0.2.15 olan yerel ipime gitmeyi denedim ve sayfaya bağlanamadı dedi herhangi bir yardım takdir edildi

**Comment by AzizKpln** [comment]
Hi,

Thanks for sharing this problem. Actually, it is not because of the tool. Tool generates a link for all networks(public). But in your case, you've tried to connect beef panel in your local network. Try to connect beef panel with the link that the tool provides. And if you want to connect your localhost via a different machine on your network, be sure that the machines are in the same network.(do not use Nat. Use nat network or bridget adapter. And dont forget that machines cant communicate eachother if they are not in the same LAN). I suggest you use bridget sdapter. Because in some cases the other networks can be a real pain in the butt
